name: Dev Environment Infrastructure Provisioning
run-name: Dev Environment Infrastructure Provisioning
on:
  workflow_dispatch:
jobs:
  terraform:
      name: Terraform Provisioning
      runs-on: ubuntu-latest
      steps:
        - name: Checkout 
          uses: actions/checkout@v4
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
        - name: Terraform Init
          run: terraform -chdir=terraform/environments/dev init