name: Dev Environment Infrastructure Provisioning
run-name: Dev Environment Infrastructure Provisioning
on:
  workflow_dispatch:
env: 
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  TF_VARS_FILE: ${{ secrets.TF_VARS_FILE }}
jobs:
  terraform:
      name: Terraform Provisioning
      runs-on: ubuntu-latest
      steps:
        - name: Checkout 
          uses: actions/checkout@v4
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
        - name: Terraform Init
          # -chdir is used to change the directory where the terraform commands runs in
          run: terraform -chdir=terraform/environments/dev init
        - name: Create terraform.tfvars file using the sored Github Secret
          run: echo "${{ env.TF_VARS_FILE }}" >> terraform.tfvars
        - name: Terraform Plan
          run: terraform -chdir=terraform/environments/dev plan -var-file=terraform.tfvars